baseURL = 'https://docs.fluffypunk.fyi/'
theme = 'hugo-book'
locale = 'en-us'
title = 'Шизофренічна документація про Linux для чайників'


[params]

BookTheme = 'dark'


[markup]

[markup.tableOfContents]
startLevel = 1
endLevel = 3
[markup.goldmark.renderer]
unsafe = true